version: '3.3'

services:
  redis:
    image: shaghayeghtvkl/shaghayegh-redis:1.0
    ports:
      - "8005:6379"
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == server-2]

  chart:
    depends_on:
      - redis
    image: shaghayeghtvkl/shaghayegh-chart:1.0
    network: host
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == server-2]

  log:
    image: shaghayeghtvkl/shaghayegh-log:1.0
    ports:
      - "8006:5000"
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == server-1]