- name: Log into DockerHub
  docker_login:
    username: shaghayeghtvkl
    password: Sh.Tv!=)13771377


- name: Build The Mag Image
  community.docker.docker_image:
    build:
      path: /home/ubuntu/log-docker/chart/
    name: shaghayegh-chart
    tag: "1.0"
    source: build



- name: Tag and Push Mag To DockerHub
  docker_image:
    name: shaghayegh-chart
    repository: shaghayeghtvkl/shaghayegh-chart
    tag: "1.0"
    push: yes

